# Generated by Django 6.0.3 on 2026-03-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_header', models.TextField(blank=True, help_text='Text shown at top of receipt')),
                ('receipt_footer', models.TextField(blank=True, default='Thank you for shopping with us!', help_text='Text shown at bottom of receipt')),
                ('show_cashier_on_receipt', models.BooleanField(default=True)),
                ('show_customer_on_receipt', models.BooleanField(default=True)),
                ('currency_symbol', models.CharField(default='Rs', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='pos.store')),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
