# Generated by Django 6.0.3 on 2026-03-12 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_loyaltytransaction_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_phone_id',
            field=models.CharField(blank=True, help_text='WhatsApp Phone Number ID from Meta dashboard', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_template_name',
            field=models.CharField(blank=True, default='receipt', help_text='Approved message template name', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_token',
            field=models.TextField(blank=True, help_text='Meta WhatsApp Cloud API Bearer token'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('sale_complete', 'Sale Completed'), ('sale_void', 'Sale Voided / Return'), ('product_add', 'Product Added'), ('product_edit', 'Product Edited'), ('product_delete', 'Product Deleted'), ('price_change', 'Price Changed'), ('stock_purchase', 'Stock Purchase'), ('expense_add', 'Expense Added'), ('expense_delete', 'Expense Deleted'), ('shift_open', 'Shift Opened'), ('shift_close', 'Shift Closed'), ('user_add', 'User Added'), ('user_edit', 'User Edited'), ('backup', 'Backup Created'), ('restore', 'Backup Restored'), ('settings_change', 'Settings Changed'), ('other', 'Other')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
