# Generated by Django 6.0.3 on 2026-03-12 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_storesettings_whatsapp_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='currency_code',
            field=models.CharField(default='PKR', max_length=10),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Rate vs base currency (1 PKR = X of this currency). Set to 1 if not converting.', max_digits=12),
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Standard VAT", "GST on Food"', max_length=100)),
                ('tax_type', models.CharField(choices=[('VAT', 'VAT (Value Added Tax)'), ('GST', 'GST (Goods & Services Tax)'), ('SALES_TAX', 'Sales Tax'), ('EXCISE', 'Excise Duty'), ('CUSTOM', 'Custom Tax')], default='SALES_TAX', max_length=20)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Percentage rate e.g. 17.000', max_digits=6)),
                ('tax_mode', models.CharField(choices=[('inclusive', 'Inclusive — tax is included in the price'), ('exclusive', 'Exclusive — tax is added on top of price')], default='exclusive', max_length=10)),
                ('apply_to', models.CharField(choices=[('all', 'All Products'), ('category', 'Specific Category Only')], default='all', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Only used if Apply To = Specific Category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.category')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='pos.store')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
