# Generated by Django 6.0.3 on 2026-03-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_storesettings_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='exchange_rate_api_key',
            field=models.CharField(blank=True, default='', help_text='Optional: ExchangeRate-API.com key for higher limits. Leave blank to use free tier.', max_length=200),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Rate vs base currency. Set to 1 if not converting.', max_digits=12),
        ),
    ]
