# Generated by Django 6.0.3 on 2026-03-16 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_storesettings_exchange_rate_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='fbr_address',
            field=models.CharField(blank=True, help_text='Business address as registered with FBR', max_length=300),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='fbr_business_name',
            field=models.CharField(blank=True, help_text='Business name as registered with FBR', max_length=200),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='fbr_enabled',
            field=models.BooleanField(default=False, help_text='Enable FBR Digital Invoicing integration'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='fbr_ntn',
            field=models.CharField(blank=True, help_text='Seller NTN (7-digit) or CNIC (13-digit)', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='fbr_province',
            field=models.CharField(blank=True, default='Punjab', help_text='Province where business is located', max_length=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='fbr_sandbox_mode',
            field=models.BooleanField(default=True, help_text='Use FBR sandbox (test) endpoint — disable for live/production'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='fbr_token',
            field=models.TextField(blank=True, help_text='FBR Security Token (Bearer token from PRAL/e.fbr.gov.pk)'),
        ),
        migrations.CreateModel(
            name='FBRInvoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('disabled', 'FBR Disabled')], default='pending', max_length=20)),
                ('fbr_invoice_no', models.CharField(blank=True, help_text='FBR-issued Invoice Reference Number (IRN)', max_length=50)),
                ('qr_code_data', models.TextField(blank=True, help_text='QR code content returned by FBR')),
                ('request_json', models.TextField(blank=True, help_text='JSON sent to FBR')),
                ('response_json', models.TextField(blank=True, help_text='Raw response from FBR')),
                ('error_message', models.TextField(blank=True)),
                ('sandbox_mode', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fbr_log', to='pos.sale')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
