# Generated by Django 6.0.3 on 2026-03-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_storesettings_fbr_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='gdrive_credentials_json',
            field=models.TextField(blank=True, help_text='Paste contents of credentials.json from Google Cloud Console'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='gdrive_enabled',
            field=models.BooleanField(default=False, help_text='Automatically upload backups to Google Drive'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, help_text='Google Drive folder ID to upload backups into (leave blank for root)', max_length=200),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='gdrive_last_backup_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful cloud backup', null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='gdrive_last_backup_url',
            field=models.TextField(blank=True, help_text='URL of the last successfully uploaded backup file'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='gdrive_token_json',
            field=models.TextField(blank=True, help_text='OAuth token — auto-filled after first authorisation'),
        ),
    ]
