# Generated by Django 6.0.3 on 2026-03-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_store_plan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='gdrive_backup_on_expense',
            field=models.BooleanField(default=False, help_text='Upload a full Excel backup to Drive on every expense entry'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='gdrive_backup_on_sale',
            field=models.BooleanField(default=False, help_text='Upload a full Excel backup to Drive on every completed sale'),
        ),
    ]
