# Generated by Django 6.0.3 on 2026-03-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_alter_store_plan_alter_store_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
