# Generated by Django 6.0.3 on 2026-03-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_store_trial_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='subdomain',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
