# Generated by Django 6.0.3 on 2026-03-31 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_store_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.store'),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('barcode', 'store')},
        ),
    ]
