# Generated by Django 6.0.3 on 2026-04-03 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_userprofile_pin_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Login Failed'), ('pin_login', 'PIN Login'), ('pin_failed', 'PIN Login Failed'), ('sale_complete', 'Sale Completed'), ('sale_void', 'Sale Voided / Return'), ('product_add', 'Product Added'), ('product_edit', 'Product Edited'), ('product_delete', 'Product Deleted'), ('price_change', 'Price Changed'), ('stock_purchase', 'Stock Purchase'), ('expense_add', 'Expense Added'), ('expense_delete', 'Expense Deleted'), ('shift_open', 'Shift Opened'), ('shift_close', 'Shift Closed'), ('user_add', 'User Added'), ('user_edit', 'User Edited'), ('backup', 'Backup Created'), ('restore', 'Backup Restored'), ('settings_change', 'Settings Changed'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fbrinvoicelog',
            name='fbr_invoice_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fbrinvoicelog',
            name='qr_code_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fbrinvoicelog',
            name='request_json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fbrinvoicelog',
            name='response_json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Rate vs base currency.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='exchange_rate_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='fbr_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='fbr_business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='fbr_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='fbr_ntn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='fbr_province',
            field=models.CharField(blank=True, default='Punjab', max_length=50),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='fbr_sandbox_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='fbr_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='gdrive_backup_on_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='gdrive_backup_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='gdrive_credentials_json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='gdrive_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='gdrive_last_backup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='gdrive_last_backup_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='gdrive_token_json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='whatsapp_phone_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='whatsapp_template_name',
            field=models.CharField(blank=True, default='receipt', max_length=100),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='whatsapp_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.category'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pin_hash',
            field=models.CharField(blank=True, help_text='Salted hash of the 4-digit PIN. Never store raw PINs.', max_length=128),
        ),
    ]
